services:
  app:
    build:
      context: .
      target: prod
    image: noahhumbert:prod
    env_file:
      - .env.prod
    container_name: prod
    ports:
      - "80:80"
    volumes: []  # does not change the container code as local changes are made
