services:
  php:
    build:
      context: .
      target: dev
    image: noahhumbert:dev
    env_file:
      - .env.dev
    container_name: dev
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/noahhumbert.com
    networks:
      - network

networks:
  network:
    external: true 