services:
  app:
    build:
      context: .
      target: test
    image: noahhumbert:test
    env_file:
      - .env.test
    container_name: test
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/noahhumbert.com