name: Deploy to Prod Env

on:
  push:
    branches:
      - main

jobs:
  restart:
    runs-on: self-hosted
    steps:
      - name: Deploy via SSH
        run: |
          docker compose -p prod -f compose.prod.yaml up -d --build
